version: '3.0'

services:
  #Monolith Services
  db:
    image: mariadb-with-resolv
    build:
      dockerfile: Dockerfile.mariadb
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    restart: always
    env_file: $PWD/env/.env.mariadb
    #environment:
      #MARIADB_ROOT_PASSWORD: /run/secrets/db_root
    networks:
      - backend
    volumes:
      - $PWD/init-db:/docker-entrypoint-initdb.d
      - $PWD/db:/var/lib/mysql

  nginx:
    image: nginx:1.18.0-alpine-fix-permissions-certbot
    build:
      dockerfile: Dockerfile.nginx
    depends_on:
      - db
      - wordpress
    volumes:
      - $PWD/nginx-ssl:/etc/ssl
      - $PWD/certbot:/etc/letsencrypt
      - $PWD/nginx:/etc/nginx
      - $PWD/wordpress:/var/www/html/wordpress
      - $PWD/cogip-src:/var/www/html/cogip
    ports:
      - '80:80'
    networks:
      - frontend

  #Individual Apps

  wordpress:
    image: wordpress-sendmail
    build:
      dockerfile: Dockerfile.wordpress
    depends_on:
      - db
    restart: always
    env_file: $PWD/env/.env.wordpress
    environment:
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_HOME','http://vmsdt-gilchrist.becode.org/wordpress');
        define('WP_SITEURL','http://vmsdt-gilchrist.becode.org/wordpress');
    working_dir: /var/www/html/wordpress
    volumes:
      - $PWD/wordpress:/var/www/html
    networks:
      - frontend
      - backend

  drupal:
    image: drupal:8-apache-subdir
    build:
      dockerfile: Dockerfile.drupal
    depends_on:
      - db
    env_file: $PWD/env/.env.drupal
    working_dir: /var/www/html/drupal
    volumes:
      - $PWD/drupal/modules:/var/www/html/drupal/modules
      - $PWD/drupal/profiles:/var/www/html/drupal/profiles
      - $PWD/drupal/themes:/var/www/html/drupal/themes
      - $PWD/drupal/sites:/var/www/html/drupal/sites
    networks:
      - frontend
      - backend
    restart: always

  cogip_php:
    #    image: php:7.4-fpm
    image: php:7.4-fpm-mysql
    build:
      dockerfile: ./Dockerfile.php
    env_file: $PWD/env/.env.cogip
    depends_on:
      - db
    volumes:
      - $PWD/cogip-src:/var/www/html
    networks:
      - frontend
      - backend

networks:
  frontend:
  backend:
#secrets:
  #cogip_admin:
    #external: true
  #db_cogip:
    #external: true
  #db_drupal:
    #external: true
  #db_root:
    #external: true
  #db_wordpress:
    #external: true
